#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mono.Samples.TexturedCube.Resource", IsApplication=true)]

namespace Mono.Samples.TexturedCube
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_texturedcube = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int f_spot = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int pattern = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int photo1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int photo10 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int photo11 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int photo12 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int photo13 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int photo14 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int photo15 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int photo16 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int photo17 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int photo18 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int photo19 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int photo20 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int photo21 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int photo22 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int photo23 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int photo24 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int photo25 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int photo3 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int photo4 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int photo5 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int photo6 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int photo7 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int photo8 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int photo9 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int translucent = 2130837532;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int paintingview = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int switch_texture = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int hide = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int show = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int switch_texture = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
