#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mono.Samples.TexturedCube.Resource", IsApplication=true)]

namespace Mono.Samples.TexturedCube
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_texturedcube = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int f_spot = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int pattern = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int photo1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int photo2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int photo3 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int photo4 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int photo5 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int photo6 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int translucent = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int paintingview = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int switch_texture = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int hide = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int show = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int switch_texture = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
